name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq shellcheck

      - name: Lint main script
        run: shellcheck cc_glm_switcher.sh

      - name: Lint test scripts
        run: shellcheck tests/*.sh

      - name: Run test suite
        run: ./tests/run_basic_tests.sh

