name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq shellcheck bat

      - name: Verify tool availability
        run: ./tests/run_all_tests.sh --check-deps

      - name: Run full test suite
        run: ./tests/run_all_tests.sh
